import os
import pandas as pd
from binance import Client
from binance.enums import HistoricalKlinesType

try: os.mkdir("Datasets")
except: pass

Assets = [
    "1INCHUSDT",
    "1000SHIBUSDT",
    "1000XECUSDT",
    "AAVEUSDT",
    "ADAUSDT",
    "AKROUSDT",
    "ALGOUSDT",
    "ALICEUSDT",
    "ALPHAUSDT",
    "ANKRUSDT",
    "ATAUSDT",
    "ATOMUSDT",
    "AUDIOUSDT",
    "AVAXUSDT",
    "AXSUSDT",
    "BAKEUSDT",
    "BALUSDT",
    "BANDUSDT",
    "BATUSDT",
    "BCHUSDT",
    "BELUSDT",
    "BLZUSDT",
    "BNBUSDT",
    "BTCUSDT",
    "BTCDOMUSDT",
    "BTSUSDT",
    "C98USDT",
    "CELRUSDT",
    "CHRUSDT",
    "CHZUSDT",
    "COMPUSDT",
    "COTIUSDT",
    "CRVUSDT",
    "CTKUSDT",
    "CVCUSDT",
    "DASHUSDT",
    "DEFIUSDT",
    "DENTUSDT",
    "DODOUSDT",
    "DOGEUSDT",
    "DOTUSDT",
    "DYDXUSDT",
    "EGLDUSDT",
    "ENJUSDT",
    "ETCUSDT",
    "ETHUSDT",
    "FILUSDT",
    "FLMUSDT",
    "FTMUSDT",
    "GALAUSDT",
    "GRTUSDT",
    "GTCUSDT",
    "HBARUSDT",
    "HNTUSDT",
    "HOTUSDT",
    "ICPUSDT",
    "ICXUSDT",
    "IOSTUSDT",
    "IOTAUSDT",
    "IOTXUSDT",
    "KAVAUSDT",
    "KEEPUSDT",
    "KNCUSDT",
    "LINAUSDT",
    "LINKUSDT",
    "LITUSDT",
    "LRCUSDT",
    "LTCUSDT",
    "LUNAUSDT",
    "MANAUSDT",
    "MASKUSDT",
    "MATICUSDT",
    "MKRUSDT",
    "MTLUSDT",
    "NEARUSDT",
    "NEOUSDT",
    "NKNUSDT",
    "OCEANUSDT",
    "OGNUSDT",
    "OMGUSDT",
    "ONEUSDT",
    "ONTUSDT",
    "QTUMUSDT",
    "RAYUSDT",
    "REEFUSDT",
    "RENUSDT",
    "RLCUSDT",
    "RSRUSDT",
    "RUNEUSDT",
    "RVNUSDT",
    "SANDUSDT",
    "SCUSDT",
    "SFPUSDT",
    "SKLUSDT",
    "SNXUSDT",
    "SOLUSDT",
    "SRMUSDT",
    "STMXUSDT",
    "STORJUSDT",
    "SXPUSDT",
    "THETAUSDT",
    "TLMUSDT",
    "TOMOUSDT",
    "TRBUSDT",
    "TRXUSDT",
    "UNFIUSDT",
    "UNIUSDT",
    "VETUSDT",
    "WAVESUSDT",
    "XEMUSDT",
    "XLMUSDT",
    "XMRUSDT",
    "XTZUSDT",
    "YFIUSDT",
    "YFIIUSDT",
    "ZECUSDT",
    "ZENUSDT",
    "ZILUSDT",
    "ZRXUSDT",
]

TimeFrame = "1h"
From = "2022/01/08"
To = "2022/02/08"

def Run(Symbol):
    pd.DataFrame(
        Client("ApiKey","ApiSecret").get_historical_klines(Symbol, TimeFrame, From, To, klines_type=HistoricalKlinesType.SPOT),
        columns=["Timestamp", "Open", "High", "Low", "Close", "Volume", None, None, None, None, None, None]).iloc[:, 0:6].to_csv(f"Datasets/{Symbol}.csv", index=False)

for Symbol in Assets:
    print(Symbol, f"{Assets.index(Symbol) + 1}/{len(Assets)}")
    while True:
        try:
            Run(Symbol)
            break
        except: pass
